mybatis:
  type-aliases-package: com.nowcoder.community.entity
  mapper-locations: /mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
logging:
  level:
    com.nowcoder.community.dao: debug
